### ISSUE TITLE
Deploy the game online (github pages perhaps?)

### ISSUE THREAD

**Issue by ashwanth1109** [ashwanth1109/dark-mario#7]

**Comment by ashwanth1109** [comment]
Github pages should be sufficient for this right?

**Comment by Rafi993** [comment]
we can use **Netlify** to setup automated deployment whenever anything gets merged into master it should be easy to do.

**Comment by Arun4033622** [comment]
> We can use **Netlify** to setup automated deployment whenever anything gets merged into master it should be easy to do.

Yeah Netlify is really good. I use it host my personal site. It is also really easy to set up.

**Comment by ashwanth1109** [comment]
Deployed to Netlify
